"""Interim raster patch of stale labels on figures that must be regenerated by the authors from raw data.
Covers the offending text with white and redraws caption-consistent labels. Documented in the figure captions."""
from PIL import Image, ImageDraw, ImageFont
import matplotlib, os
FONT=os.path.join(os.path.dirname(matplotlib.__file__),'mpl-data/fonts/ttf/DejaVuSans.ttf')
def font(sz): return ImageFont.truetype(FONT, sz)
def cover(d, box): d.rectangle(box, fill='white')
def ctext(d, cx, y, s, sz, fill='black'):
    f=font(sz); w=d.textlength(s, font=f); d.text((cx-w/2, y), s, font=f, fill=fill)

# ---- Figure 1: structures (3423 x 1971) ----
im=Image.open('Fig1_structures_relabel_required.png').convert('RGB'); W,H=im.size; d=ImageDraw.Draw(im)
sx, sy = W/2000, H/1152
cover(d, (0, 150*sy, W, 240*sy))
ctext(d, 430*sx, 160*sy, "(a) Pr-substituted anatase TiO₂ with V_O", int(30*sx))
ctext(d, 430*sx, 200*sy, "PrTi₁₅O₃₁, 47 atoms; m = 0 (non-magnetic solution)", int(28*sx))
ctext(d, 1555*sx, 160*sy, "(b) Rb-substituted anatase TiO₂ with V_O", int(30*sx))
ctext(d, 1555*sx, 200*sy, "RbTi₁₅O₃₁, 47 atoms; m = −0.97 μB, m_abs = 1.21 μB", int(28*sx))
im.save('Fig1_structures_patched.png'); print('Fig1', W, H)

# ---- Figure 4: spin-resolved PDOS ----
im=Image.open('Fig4_PDOS_relabel_required.png').convert('RGB'); W,H=im.size; d=ImageDraw.Draw(im)
sx, sy = W/1400, H/1548
cover(d, (0, 10*sy, W, 70*sy))
ctext(d, 700*sx, 22*sy, "Spin-resolved PDOS: Pr_VO (non-magnetic) vs Rb_VO (one unpaired spin)", int(28*sx))
cover(d, (150*sx, 150*sy, 700*sx, 195*sy))
d.text((175*sx, 158*sy), "Pr_VO (non-magnetic, E_F = 10.31 eV)", font=font(int(27*sx)), fill='black')
cover(d, (150, 782, 780, 852))
d.text((175, 798), "Rb_VO (m_abs = 1.21 μB, E_F = 7.14 eV)", font=font(int(27*sx)), fill='black')
cover(d, (278, 1118, 415, 1172))
d.text((288, 1130), "gap state", font=font(int(21*sx)), fill='#1f3a6e')
im.save('Fig4_PDOS_patched.png'); print('Fig4', W, H)

# ---- Figure S1: Pr_VO PDOS with dopant channels (2372 x 1448) ----
im=Image.open('FigS1_PrVO_PDOS_relabel_required.png').convert('RGB'); W,H=im.size; d=ImageDraw.Draw(im)
sx, sy = W/2000, H/1221
cover(d, (1725*sx, 252*sy, 1990*sx, 306*sy))      # 'Pr 4f' legend entry
cover(d, (198*sx, 148*sy, 845*sx, 265*sy))        # green interpretive box
im.save('FigS1_PrVO_PDOS_patched.png'); print('FigS1', W, H)

# ---- Figure S2: total PDOS ----
im=Image.open('FigS2_total_PDOS.png').convert('RGB'); W,H=im.size; d=ImageDraw.Draw(im)
sx, sy = W/1400, H/1390
cover(d, (100*sx, 118*sy, 620*sx, 162*sy))
d.text((115*sx, 126*sy), "Pr_VO (non-magnetic, E_F = 10.31 eV)", font=font(int(26*sx)), fill='black')
cover(d, (100*sx, 712*sy, 700*sx, 758*sy))
d.text((115*sx, 720*sy), "Rb_VO (m_abs = 1.21 μB, E_F = 7.14 eV)", font=font(int(26*sx)), fill='black')
im.save('FigS2_total_PDOS_patched.png'); print('FigS2', W, H)
